export const AVALAIBLE_LOCATION = [
    "Antananarivo",
    "Ambohimanga",
    "Miarinarivo",
    "Arivonimamo",
    "Antsirabe",
    "Betafo",
    "Ambatolampy",
    "Tsiroanomandidy",
    "Fianarantsoa",
    "Ambositra",
    "Manandriana",
    "Mananjary",
    "Nosy Varika",
    "Manakara",
    "Vohipeno",
    "Farafangana",
    "Vangaindrano",
    "Ihosy",
    "Tolagnaro",
    "Ambovombe",
    "Bekily",
    "Toliara",
    "Betioky",
    "Ankazoabo",
    "Morondava",
    "Belo-sur-Tsiribihina",
    "Maintirano",
    "Antsalova",
    "Mahajanga",
    "Marovoay",
    "Antsohihy",
    "Bealanana",
    "Andilamena",
    "Maevatanana",
    "Ambatondrazaka",
    "Amparafaravola",
    "Fenoarivo Atsinanana",
    "Sainte-Marie",
    "Sambava",
    "Andapa",
    "Antalaha",
    "Vohémar",
    "Antsiranana",
    "Ambilobe",
    "Nosy Be",
    "Ambanja"
];
